version: "3.7"
services:
########################################
#traefix - reverse proxy
########################################
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8082:8080"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --certificatesresolvers.leresolver.acme.email=tdelesio@gmail.com
      - --certificatesresolvers.leresolver.acme.storage=/etc/traefix/acme/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=admin:rage311"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"



#      - "traefik.enable=true"
#      - "traefik.backend=traefik"
#      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
#      #      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
#      - "traefik.port=8080"
#      - "traefik.docker.network=traefik_proxy"
#      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.SSLHost=delesio.com"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=true"
#      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/storage/dockerdata/traefikv2:/etc/traefik


  ########################################
  #watch tower - container updater
  ########################################
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

########################################
#plex - media server
########################################
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /mnt/storage/dockerdata/plex:/config
      - /mnt/nas/home_movies:/data/home_movies
      - /mnt/nas/photos:/data/photos
      - /mnt/storage/media/tv:/data/tvshows
      - /mnt/storage/media/movies:/data/movies
      - /mnt/storage/media/christmas:/data/christmas
      - /mnt/storage/media/kids:/data/kids
      - /mnt/storage/media/4kmovies:/data/4kmovies
      - /mnt/storage/tmp:/transcode
    network_mode: host
    restart: always
    environment:
      - VERSION=public
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ADVERTISE_IP="http://10.0.0.10:32400/"
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ALLOWED_NETWORKS=10.0.0.0/8



  ########################################
  #sonarr - tv media organizer - 8989
  ########################################
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /mnt/storage/dockerdata/sonarr:/config
      - /mnt/storage/media/tv:/tv
      - /mnt/nas/plex_server/downloads/complete:/downloads
    #    ports:
    #      - 8989:8989
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - traefik.http.routers.sonarr.rule=Host(`delesio.com`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=sonarr"
#      - "traefik.frontend.rule=Host:tv.${DOMAINNAME}"
#      - "traefik.port=8989"
#      - "traefik.docker.network=traefik_proxy"
#      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.SSLHost=delesio.com"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=false"

  ########################################
#  radarr:
#    image: linuxserver/radarr
#    container_name: radarr
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - UMASK_SET=022 #optional
#    volumes:
#      - /mnt/storage/dockerdata/radarr:/config
#      - /mnt/storage/media/movies:/movies
#      - /mnt/storage/media/kids:/kids
#      - /mnt/storage/media/christmas:/christmas
#      - /mnt/storage/media/4kmovies:/4kmovies
#      - /mnt/nas/plex_server/downloads/complete:/downloads
#    ports:
#      - 7878:7878
#    restart: unless-stopped
#    networks:
#      - traefik_proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=radarr"
#      - "traefik.frontend.rule=Host:movies.${DOMAINNAME}"
#      - "traefik.port=7878"
#      - "traefik.docker.network=traefik_proxy"
#      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.SSLHost=delesio.com"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=false"
#
#  ########################################
#  readarr:
#    image: hotio/readarr:nightly
#    container_name: readarr
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - UMASK_SET=002 #optional
#    volumes:
#      - /mnt/storage/dockerdata/readarr:/config
#      - /mnt/nas/plex_server/downloads/complete:/downloads
#      - /mnt/storage/media/books/ebooks:/books
#    ports:
#      - 8787:8787
#    restart: unless-stopped
#    networks:
#      - traefik_proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=readarr"
#      - "traefik.frontend.rule=Host:books.${DOMAINNAME}"
#      - "traefik.port=8787"
#      - "traefik.docker.network=traefik_proxy"
#      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.SSLHost=delesio.com"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=false"
#
#  ubooquity:
#    image: ghcr.io/linuxserver/ubooquity
#    container_name: ubooquity
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=${TZ}
#    volumes:
#      - /mnt/storage/dockerdata/ubooquity:/config
#      - /mnt/storage/media/books/ebooks:/books
#    ports:
#      - 2202:2202
#      - 2203:2203
#    restart: unless-stopped
#    networks:
#      - traefik_proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=ubooquity"
#      - "traefik.frontend.rule=Host:opds.${DOMAINNAME}"
#      # ;AddPrefix:/ubooquity/opds-books"
#      - "traefik.port=2202"
#      - "traefik.docker.network=traefik_proxy"
#      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.SSLHost=delesio.com"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=false"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge